/*
 * Calculator API
 *
 * API that performs arithmetic operations on two numeric values.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;

namespace SimpleCalculatorService.Models
{
    /// <summary>
    /// Calculate Body
    /// </summary>
    [DataContract]
    public partial class CalculateBody : IEquatable<CalculateBody>
    {
        /// <summary>
        /// Gets or Sets Number1
        /// </summary>
        [Required]

        [DataMember(Name = "number1")]
        public decimal? Number1 { get; set; }

        /// <summary>
        /// Gets or Sets Number2
        /// </summary>
        [Required]

        [DataMember(Name = "number2")]
        public decimal? Number2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CalculateBody {\n");
            sb.Append("  Number1: ").Append(Number1).Append("\n");
            sb.Append("  Number2: ").Append(Number2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, new JsonSerializerOptions { WriteIndented = true });
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CalculateBody)obj);
        }

        /// <summary>
        /// Returns true if CalculateBody instances are equal
        /// </summary>
        /// <param name="other">Instance of CalculateBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CalculateBody? other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Number1 == other.Number1 ||
                    Number1 != null &&
                    Number1.Equals(other.Number1)
                ) &&
                (
                    Number2 == other.Number2 ||
                    Number2 != null &&
                    Number2.Equals(other.Number2)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Number1 != null)
                    hashCode = HashCode.Combine(hashCode, Number1.GetHashCode());
                if (Number2 != null)
                    hashCode = HashCode.Combine(hashCode, Number2.GetHashCode());
                return hashCode;
            }
        }

        #region Operators

        /// <summary>
        /// Checks if two CalculateBody instances are equal.
        /// </summary>
        /// <param name="left">The first CalculateBody instance.</param>
        /// <param name="right">The second CalculateBody instance.</param>
        /// <returns>True if both instances are equal, otherwise false.</returns>
        public static bool operator ==(CalculateBody left, CalculateBody right) => Equals(left, right);

        /// <summary>
        /// Checks if two CalculateBody instances are not equal.
        /// </summary>
        /// <param name="left">The first CalculateBody instance.</param>
        /// <param name="right">The second CalculateBody instance.</param>
        /// <returns>True if both instances are not equal, otherwise false.</returns>
        public static bool operator !=(CalculateBody left, CalculateBody right) => !Equals(left, right);

        #endregion Operators
    }
}
